/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.colocasian.math;

import org.junit.Test;
import static org.junit.Assert.*;

public class ExpressionTest {
    @Test public void testEvaluation() {
        Expression evaluator = new Expression();

        double[] tests = new double[]{
                evaluator.evaluate("{[84/7]^2-9}*10+10"),
                evaluator.evaluate("[(-4) + {(-8) / (-4)}] * (-2) * (-2) - (-7)"),
                evaluator.evaluate("7 - (-5)*[3-{3^2 +(- 5) }]"),
                evaluator.evaluate("[(-3)- {( -6) / (-3) } ^ 2] * (-11) + (- 11)")
        };

        double[] answers = new double[]{
                1360.,
                -1.,
                2.,
                66.
        };

        assertArrayEquals("Test anwers should match actual answers", tests, answers, 1e-6);
    }
}
